server:
  port: 10000
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://gulimall:3306/gulimall_pms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: nacos1:4001
    sentinel:
      transport:
        dashboard: localhost:8080
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: gulimall
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: true
      cache-null-values: true
  zipkin:
    base-url: http://gulimall:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.tzp.gulimall: info

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
