server:
  port: 15001
spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: nacos1:4001
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
  thymeleaf:
    cache: false
  redis:
    host: gulimall
    port: 6379
  #配置异步任务线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  rabbitmq:
    host: gulimall
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  zipkin:
    base-url: http://gulimall:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1


#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
