server:
  port: 12001
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: nacos1:4001
    sentinel:
      transport:
        dashboard: localhost:8080
  thymeleaf:
    cache: false
  redis:
    host: gulimall
    port: 6379
  zipkin:
    base-url: http://gulimall:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

elastic:
  hostname: 10.0.0.40
  post: 9200
