server:
  port: 14001

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: nacos1:4001
    sentinel:
      transport:
        dashboard: localhost:8080
  redis:
    port: 6379
    host: gulimall
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://gulimall:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10




